In [48]:
import pandas as pd

In [60]:
audio = pd.read_csv('../Feature Extraction/audio_sarcasm_dataset.csv')
audio.columns

Index(['Unnamed: 0', 'sarcasm_label', 'emotion_label', 'sentiment_label', 'id',
       'sentence_level_similarity_emotion', 'sentence_level_similarity_word',
       'exclamation', 'AUDIO_1', 'AUDIO_2', 'AUDIO_3', 'AUDIO_4', 'AUDIO_5',
       'AUDIO_6', 'AUDIO_7', 'AUDIO_8'],
      dtype='object')

In [61]:
# Assuming df is your DataFrame
audio.rename(columns={
    'AUDIO_1': 'PCA_MFCC_1',
    'AUDIO_2': 'PCA_MFCC_2',
    'AUDIO_3': 'PCA_MFCC_3',
    'AUDIO_4': 'PCA_MFCC_4',
    'AUDIO_5': 'PCA_MFCC_5',
    'AUDIO_6': 'PCA_MFCC_6',
    'AUDIO_7': 'PCA_MFCC_7',
    'AUDIO_8': 'PCA_MFCC_8'
}, inplace=True)

In [51]:
audio

,Unnamed: 0,sarcasm_label,emotion_label,sentiment_label,id,sentence_level_similarity_emotion,sentence_level_similarity_word,exclamation,PCA_MFCC_1,PCA_MFCC_2,PCA_MFCC_3,PCA_MFCC_4,PCA_MFCC_5,PCA_MFCC_6,PCA_MFCC_7,PCA_MFCC_8
0,0,0,anger,0,1,0.000000,0.000000,0,-2.276627,1.194254,1.073762,-0.120506,-0.308371,0.027054,-0.521969,-1.144353
1,1,0,anger,0,2,0.000000,0.000000,0,-0.920419,-0.245156,1.557069,-0.234828,0.540239,1.073943,0.077584,1.199006
2,2,0,anger,0,3,0.439865,0.913640,0,-1.511857,-0.118752,0.132647,-0.888176,0.340909,-1.137311,0.961322,1.532151
3,3,0,anger,0,4,0.009295,0.920026,1,-1.032136,1.556911,0.385882,-0.252339,-0.164264,-0.412079,-0.039664,-0.533009
4,4,0,anger,0,5,0.000000,0.000000,1,0.139397,-0.984472,0.358380,0.581564,-0.502099,-0.111040,0.787407,0.286733
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,419,0,surprise,0,420,0.000000,0.000000,0,-1.219419,0.458677,2.047222,0.538345,1.131656,-0.402536,-0.563440,0.952709
255,421,0,surprise,0,422,-0.688249,0.938817,0,-0.195316,-0.250842,-0.458744,-0.920555,-0.709591,-0.709534,-0.109214,-0.370972
256,422,0,surprise,0,423,0.000000,0.000000,1,2.020319,2.749040,-0.155967,-0.044834,0.379603,0.893045,-0.124065,1.150491
257,425,0,surprise,0,426,0.779693,0.706350,1,-1.857867,1.587987,-0.524588,-0.655474,-1.968691,0.052819,-1.107251,0.223600
258,427,0,surprise,0,428,0.000000,0.000000,0,-2.124620,-0.969605,2.702946,-0.300067,0.464363,0.705530,-0.208636,0.481005

In [67]:
text = pd.read_csv('../Feature Extraction/text_sentiment_dataset.csv')

# Assuming df is your DataFrame
text.rename(columns={
    f'TEXT_{i}': f'PCA_W2V_{i}' for i in range(1, 51)  # This creates mappings from TEXT_1 to TEXT_50
}, inplace=True)

text

,Unnamed: 0,sarcasm_label,emotion_label,sentiment_label,id,sentence_level_similarity_emotion,sentence_level_similarity_word,exclamation,PCA_W2V_1,PCA_W2V_2,...,PCA_W2V_41,PCA_W2V_42,PCA_W2V_43,PCA_W2V_44,PCA_W2V_45,PCA_W2V_46,PCA_W2V_47,PCA_W2V_48,PCA_W2V_49,PCA_W2V_50
0,6,0,anger,0,7,0.418089,0.925549,0,4.246306,8.633176,...,-0.934766,-0.325562,-0.974762,0.703293,1.427808,-2.302098,1.498136,-0.543049,-2.493170,-1.957749
1,9,0,anger,0,10,0.871597,0.748983,0,4.085410,-5.867634,...,0.904332,-0.459146,-2.648103,-0.636127,-0.826573,-0.372217,1.195686,-0.340679,-0.715276,-0.064174
2,10,0,anger,0,11,0.505245,0.967032,0,-7.414406,11.927856,...,-2.649308,1.650261,3.071791,0.195687,0.480996,-4.687943,2.448713,0.666633,-1.041592,-4.172806
3,15,0,anger,0,16,0.493705,0.877538,1,4.807814,-4.929314,...,-2.225688,1.561609,1.266199,2.161878,2.607816,2.183959,-2.469064,2.251464,-0.766235,2.765786
4,16,0,anger,0,17,0.000000,0.000000,0,0.636560,-1.053120,...,-4.390137,3.715597,-3.007263,0.781607,1.176396,-3.338664,2.820811,-3.073105,2.004135,-5.080381
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,420,0,surprise,1,421,0.000000,0.000000,0,3.248508,-3.661104,...,-5.452966,1.512089,3.138302,-1.555502,-2.080518,-2.237268,1.325341,-1.126117,1.575610,3.992722
166,423,0,surprise,1,424,0.989552,0.895404,0,3.054822,-5.435869,...,-0.986096,-1.390669,-0.063719,-0.142470,-0.183707,2.323386,1.483013,1.125637,-0.627649,0.198293
167,424,0,surprise,0,425,0.000000,0.000000,0,6.315460,0.864717,...,-1.901199,0.380718,2.439599,-1.031472,2.011512,0.079433,-3.110928,1.486013,-0.568575,3.123471
168,426,0,surprise,0,427,0.241069,0.913709,0,1.040925,7.243415,...,-2.339568,-1.523893,-0.459625,-0.256269,1.330352,0.973506,-0.163107,-0.691206,-0.604612,1.004810
169,428,0,surprise,1,429,0.123383,0.857455,0,-1.695781,-2.786950,...,-1.278508,1.921889,-1.448516,-2.328229,1.849088,-1.400628,3.012614,0.365956,-0.343399,0.524265

In [69]:
text = text[['id', 'PCA_W2V_1', 'PCA_W2V_2', 'PCA_W2V_3', 'PCA_W2V_4',
       'PCA_W2V_5', 'PCA_W2V_6', 'PCA_W2V_7', 'PCA_W2V_8', 'PCA_W2V_9',
       'PCA_W2V_10', 'PCA_W2V_11', 'PCA_W2V_12', 'PCA_W2V_13', 'PCA_W2V_14',
       'PCA_W2V_15', 'PCA_W2V_16', 'PCA_W2V_17', 'PCA_W2V_18', 'PCA_W2V_19',
       'PCA_W2V_20', 'PCA_W2V_21', 'PCA_W2V_22', 'PCA_W2V_23', 'PCA_W2V_24',
       'PCA_W2V_25', 'PCA_W2V_26', 'PCA_W2V_27', 'PCA_W2V_28', 'PCA_W2V_29',
       'PCA_W2V_30', 'PCA_W2V_31', 'PCA_W2V_32', 'PCA_W2V_33', 'PCA_W2V_34',
       'PCA_W2V_35', 'PCA_W2V_36', 'PCA_W2V_37', 'PCA_W2V_38', 'PCA_W2V_39',
       'PCA_W2V_40', 'PCA_W2V_41', 'PCA_W2V_42', 'PCA_W2V_43', 'PCA_W2V_44',
       'PCA_W2V_45', 'PCA_W2V_46', 'PCA_W2V_47', 'PCA_W2V_48', 'PCA_W2V_49',
       'PCA_W2V_50']]

In [70]:
audio

,Unnamed: 0,sarcasm_label,emotion_label,sentiment_label,id,sentence_level_similarity_emotion,sentence_level_similarity_word,exclamation,PCA_MFCC_1,PCA_MFCC_2,PCA_MFCC_3,PCA_MFCC_4,PCA_MFCC_5,PCA_MFCC_6,PCA_MFCC_7,PCA_MFCC_8
0,0,0,anger,0,1,0.000000,0.000000,0,-2.276627,1.194254,1.073762,-0.120506,-0.308371,0.027054,-0.521969,-1.144353
1,1,0,anger,0,2,0.000000,0.000000,0,-0.920419,-0.245156,1.557069,-0.234828,0.540239,1.073943,0.077584,1.199006
2,2,0,anger,0,3,0.439865,0.913640,0,-1.511857,-0.118752,0.132647,-0.888176,0.340909,-1.137311,0.961322,1.532151
3,3,0,anger,0,4,0.009295,0.920026,1,-1.032136,1.556911,0.385882,-0.252339,-0.164264,-0.412079,-0.039664,-0.533009
4,4,0,anger,0,5,0.000000,0.000000,1,0.139397,-0.984472,0.358380,0.581564,-0.502099,-0.111040,0.787407,0.286733
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,419,0,surprise,0,420,0.000000,0.000000,0,-1.219419,0.458677,2.047222,0.538345,1.131656,-0.402536,-0.563440,0.952709
255,421,0,surprise,0,422,-0.688249,0.938817,0,-0.195316,-0.250842,-0.458744,-0.920555,-0.709591,-0.709534,-0.109214,-0.370972
256,422,0,surprise,0,423,0.000000,0.000000,1,2.020319,2.749040,-0.155967,-0.044834,0.379603,0.893045,-0.124065,1.150491
257,425,0,surprise,0,426,0.779693,0.706350,1,-1.857867,1.587987,-0.524588,-0.655474,-1.968691,0.052819,-1.107251,0.223600
258,427,0,surprise,0,428,0.000000,0.000000,0,-2.124620,-0.969605,2.702946,-0.300067,0.464363,0.705530,-0.208636,0.481005

In [54]:
merged_df = audio.merge(text, on='id', suffixes=('_audio', '_text'))

# Filter out the _text columns that have a corresponding _audio column
for col in merged_df.columns:
    if col.endswith('_text'):
        audio_col = col.replace('_text', '_audio')
        if audio_col in merged_df.columns:
            merged_df.drop(col, axis=1, inplace=True)  # Drop the text column if the audio column exists
        else:
            # Rename back to original if no corresponding audio column exists
            merged_df.rename(columns={col: col.replace('_text', '')}, inplace=True)

# Optionally, rename columns to remove the suffix from audio columns where no overlap occurred
for col in merged_df.columns:
    if col.endswith('_audio'):
        merged_df.rename(columns={col: col.replace('_audio', '')}, inplace=True)

# Now merged_df contains all columns from 'audio' and only non-overlapping columns from 'text'

In [56]:
sum(merged_df.sarcasm_label)

69

In [57]:
merged_df.to_csv('sarcasm_final.csv')

In [ ]:
merged_df = audio.merge(text, on='id', suffixes=('_audio', '_text'))

# Filter out the _text columns that have a corresponding _audio column
for col in merged_df.columns:
    if col.endswith('_text'):
        audio_col = col.replace('_text', '_audio')
        if audio_col in merged_df.columns:
            merged_df.drop(col, axis=1, inplace=True)  # Drop the text column if the audio column exists
        else:
            # Rename back to original if no corresponding audio column exists
            merged_df.rename(columns={col: col.replace('_text', '')}, inplace=True)

# Optionally, rename columns to remove the suffix from audio columns where no overlap occurred
for col in merged_df.columns:
    if col.endswith('_audio'):
        merged_df.rename(columns={col: col.replace('_audio', '')}, inplace=True)

# Now merged_df contains all columns from 'audio' and only non-overlapping columns from 'text'

In [42]:
merged_df.columns

Index(['Unnamed: 0', 'sarcasm_label', 'emotion_label', 'sentiment_label', 'id',
       'sentence_level_similarity_emotion', 'sentence_level_similarity_word',
       'exclamation', 'PCA_MFCC_1', 'PCA_MFCC_2', 'PCA_MFCC_3', 'PCA_MFCC_4',
       'PCA_MFCC_5', 'PCA_MFCC_6', 'PCA_MFCC_7', 'PCA_MFCC_8', 'PCA_W2V_1',
       'PCA_W2V_2', 'PCA_W2V_3', 'PCA_W2V_4', 'PCA_W2V_5', 'PCA_W2V_6',
       'PCA_W2V_7', 'PCA_W2V_8', 'PCA_W2V_9', 'PCA_W2V_10', 'PCA_W2V_11',
       'PCA_W2V_12', 'PCA_W2V_13', 'PCA_W2V_14', 'PCA_W2V_15', 'PCA_W2V_16',
       'PCA_W2V_17', 'PCA_W2V_18', 'PCA_W2V_19', 'PCA_W2V_20', 'PCA_W2V_21',
       'PCA_W2V_22', 'PCA_W2V_23', 'PCA_W2V_24', 'PCA_W2V_25', 'PCA_W2V_26',
       'PCA_W2V_27', 'PCA_W2V_28', 'PCA_W2V_29', 'PCA_W2V_30', 'PCA_W2V_31',
       'PCA_W2V_32', 'PCA_W2V_33', 'PCA_W2V_34', 'PCA_W2V_35', 'PCA_W2V_36',
       'PCA_W2V_37', 'PCA_W2V_38', 'PCA_W2V_39', 'PCA_W2V_40', 'PCA_W2V_41',
       'PCA_W2V_42', 'PCA_W2V_43', 'PCA_W2V_44', 'PCA_W2V_45', 'PCA_W2V_46',
       'PCA_W2V_47', 'PCA_W2V_48', 'PCA_W2V_49', 'PCA_W2V_50', 'PCA_51',
       'PCA_52', 'PCA_53', 'PCA_54', 'PCA_55', 'PCA_56', 'PCA_57', 'PCA_58',
       'PCA_59', 'PCA_60', 'spectral_centroid', 'spectral_bandwidth', 'pitch'],
      dtype='object')

In [58]:
ref = pd.read_csv('../datasets/sarcasm_final.csv')
set(ref.columns) - set(merged_df.columns)

{'energy',
 'loudness',
 'mfccs_1',
 'mfccs_10',
 'mfccs_11',
 'mfccs_12',
 'mfccs_13',
 'mfccs_2',
 'mfccs_3',
 'mfccs_4',
 'mfccs_5',
 'mfccs_6',
 'mfccs_7',
 'mfccs_8',
 'mfccs_9'}

In [59]:
merged_df.columns

Index(['Unnamed: 0', 'sarcasm_label', 'emotion_label', 'sentiment_label', 'id',
       'sentence_level_similarity_emotion', 'sentence_level_similarity_word',
       'exclamation', 'PCA_MFCC_1', 'PCA_MFCC_2', 'PCA_MFCC_3', 'PCA_MFCC_4',
       'PCA_MFCC_5', 'PCA_MFCC_6', 'PCA_MFCC_7', 'PCA_MFCC_8', 'PCA_W2V_1',
       'PCA_W2V_2', 'PCA_W2V_3', 'PCA_W2V_4', 'PCA_W2V_5', 'PCA_W2V_6',
       'PCA_W2V_7', 'PCA_W2V_8', 'PCA_W2V_9', 'PCA_W2V_10', 'PCA_W2V_11',
       'PCA_W2V_12', 'PCA_W2V_13', 'PCA_W2V_14', 'PCA_W2V_15', 'PCA_W2V_16',
       'PCA_W2V_17', 'PCA_W2V_18', 'PCA_W2V_19', 'PCA_W2V_20', 'PCA_W2V_21',
       'PCA_W2V_22', 'PCA_W2V_23', 'PCA_W2V_24', 'PCA_W2V_25', 'PCA_W2V_26',
       'PCA_W2V_27', 'PCA_W2V_28', 'PCA_W2V_29', 'PCA_W2V_30', 'PCA_W2V_31',
       'PCA_W2V_32', 'PCA_W2V_33', 'PCA_W2V_34', 'PCA_W2V_35', 'PCA_W2V_36',
       'PCA_W2V_37', 'PCA_W2V_38', 'PCA_W2V_39', 'PCA_W2V_40', 'PCA_W2V_41',
       'PCA_W2V_42', 'PCA_W2V_43', 'PCA_W2V_44', 'PCA_W2V_45', 'PCA_W2V_46',
       'PCA_W2V_47', 'PCA_W2V_48', 'PCA_W2V_49', 'PCA_W2V_50', 'PCA_W2V_51',
       'PCA_W2V_52', 'PCA_W2V_53', 'PCA_W2V_54', 'PCA_W2V_55', 'PCA_W2V_56',
       'PCA_W2V_57', 'PCA_W2V_58', 'PCA_W2V_59', 'PCA_W2V_60',
       'spectral_centroid', 'spectral_bandwidth', 'pitch'],
      dtype='object')